export const travelerPersonas = [
  {
    id: 'general',
    slug: 'general-traveler',
    name: 'General Traveler & Tourist',
    emoji: '✈️',
    svgIcon: 'plane',
    tagline: 'Stay healthy on any trip',
    description: 'Tourists, holiday travelers, and anyone exploring a new country who wants to eat safely and stay well.',
    heroHeadline: 'Stay healthy everywhere you go',
    heroSub: 'Food safety, nutrition tips, and health guidance for every destination — tailored to your dietary needs.',
    topConcerns: ['Food safety by country', 'Managing allergies abroad', 'Water safety', 'Avoiding traveler\'s diarrhea', 'Eating with medical conditions', 'Reading food labels in foreign languages'],
    sampleQuestion: 'I have a nut allergy and I am traveling to Thailand next month. Which dishes should I avoid?',
    color: '#1D9E75',
    lightColor: '#E1F5EE',
    systemPromptAddition: 'The user is a general tourist or holiday traveler. Focus on practical food safety, allergen awareness, water safety, and managing any dietary conditions while sightseeing and dining out at local restaurants.',
    metaTitle: 'NomadVital for Travelers — Eat Safely in Any Country',
    metaDescription: 'Get AI-powered food safety and nutrition guidance for your next holiday. Know what to eat, what to avoid, and how to stay healthy in 50+ countries.',
    pageUrl: '/for/general-traveler',
  },
  {
    id: 'marathon',
    slug: 'marathon-runners',
    name: 'Marathon & Ultra Runners',
    emoji: '🏃',
    svgIcon: 'runner',
    tagline: 'Race nutrition, wherever you race',
    description: 'Marathon runners, ultramarathon athletes, and distance runners traveling internationally for races and events.',
    heroHeadline: 'Fuel your international race',
    heroSub: 'Pre-race carb loading, race-day nutrition, and recovery eating — tailored for runners competing abroad at World Majors and beyond.',
    topConcerns: ['Carb loading foods available locally', 'Race-day GI safety — avoiding stomach issues', 'Post-race recovery nutrition', 'Jet lag and nutrition timing', 'Hydration in unfamiliar climates', 'Finding familiar race fuel abroad'],
    sampleQuestion: 'I am running the Tokyo Marathon next month. What local foods are best for carb loading the night before? What should I avoid to prevent GI issues on race day?',
    color: '#D85A30',
    lightColor: '#FAECE7',
    systemPromptAddition: 'The user is a marathon or ultramarathon runner traveling internationally for a race. Prioritise: pre-race carb loading options available locally, race-day GI safety (avoiding foods that cause stomach issues during running), post-race recovery nutrition, jet lag management with food timing, and finding familiar race fuel like gels and electrolytes in the destination country. Always mention what to EAT and what to AVOID specifically for runners in this destination.',
    metaTitle: 'NomadVital for Runners — Race Nutrition Guide for International Marathons',
    metaDescription: 'AI-powered nutrition guide for marathon and ultramarathon runners competing abroad. Carb loading, race-day GI safety, and recovery nutrition for every destination.',
    pageUrl: '/for/marathon-runners',
  },
  {
    id: 'ironman',
    slug: 'ironman-triathlete',
    name: 'Ironman & Triathlete',
    emoji: '🏊',
    svgIcon: 'triathlete',
    tagline: 'Multi-sport nutrition abroad',
    description: 'Ironman competitors, triathletes, and multi-sport athletes traveling for international events requiring peak performance nutrition.',
    heroHeadline: 'Perform at your best, anywhere',
    heroSub: 'Swim-bike-run nutrition planning, electrolyte management, and safe protein sources — for triathletes competing at international Ironman events.',
    topConcerns: ['Electrolyte management in heat and humidity', 'Safe high-protein foods by country', 'Supplement availability at destination', 'Early morning race nutrition (4–5am start times)', 'Multi-day training nutrition', 'Recovery nutrition after 8+ hour race days'],
    sampleQuestion: 'I am doing Ironman Malaysia next month. The heat and humidity will be extreme. What electrolyte foods are available locally and how should I adjust my nutrition in the final week before the race?',
    color: '#185FA5',
    lightColor: '#E6F1FB',
    systemPromptAddition: 'The user is an Ironman or triathlete competing internationally. They need highly specific, performance-focused nutrition guidance. Priorities: electrolyte management for heat and humidity specific to the destination, local sources of quality protein, supplement availability at the destination country, very early race morning nutrition (4-5am starts), multi-day heavy training nutrition, and recovery from 8-12 hour race days. Mention specific local foods and where to find them. These athletes have high nutritional literacy — give detailed, specific answers.',
    metaTitle: 'NomadVital for Triathletes — Ironman Nutrition Guide for International Races',
    metaDescription: 'AI-powered nutrition guidance for Ironman and triathlete athletes competing internationally. Electrolytes, protein sources, supplements, and race-day fuelling for every destination.',
    pageUrl: '/for/ironman-triathlete',
  },
  {
    id: 'mountaineer',
    slug: 'mountaineers-trekkers',
    name: 'Mountaineer & Trekker',
    emoji: '🧗',
    svgIcon: 'mountain',
    tagline: 'Altitude nutrition and mountain food safety',
    description: 'Mountaineers, trekkers, and altitude athletes heading to the Himalayas, Andes, Alps, Kilimanjaro, and other high-altitude destinations.',
    heroHeadline: 'Nutrition for the heights',
    heroSub: 'High-altitude food safety, calorie density planning, AMS nutrition support, and clean water guidance for mountaineers and trekkers worldwide.',
    topConcerns: ['High-altitude nutrition — calorie needs increase at elevation', 'AMS (Acute Mountain Sickness) — foods that help and hurt acclimatisation', 'Clean water sources on the trail', 'Calorie-dense foods available locally for packing', 'Food safety in remote areas with no refrigeration', 'Iron and oxygen-carrying nutrition for altitude performance'],
    sampleQuestion: 'I am trekking to Everest Base Camp next month. What should I eat during the acclimatisation days? Are there foods to avoid that worsen altitude sickness?',
    color: '#3B6D11',
    lightColor: '#EAF3DE',
    systemPromptAddition: 'The user is a mountaineer or trekker going to high-altitude destinations. Key priorities: calorie needs at altitude (significantly higher than sea level), foods that support acclimatisation and reduce AMS risk, foods that worsen AMS (avoid alcohol, heavy fats initially), iron-rich foods for oxygen-carrying capacity, clean water sources and purification, calorie-dense local foods for carrying on the trail, and food safety without refrigeration in remote areas. Mention altitude-specific physiology simply and practically.',
    metaTitle: 'NomadVital for Mountaineers — High Altitude Nutrition and Food Safety Guide',
    metaDescription: 'Nutrition guidance for mountaineers and trekkers. High-altitude calorie needs, AMS-friendly foods, clean water sources, and food safety for Himalayas, Andes, Alps and beyond.',
    pageUrl: '/for/mountaineers-trekkers',
  },
  {
    id: 'business',
    slug: 'business-travelers',
    name: 'Business Traveler',
    emoji: '💼',
    svgIcon: 'briefcase',
    tagline: 'Eat well, perform better on the road',
    description: 'Frequent business travelers who want to maintain energy, manage jet lag, eat healthily in hotels and airports, and stay sharp on work trips.',
    heroHeadline: 'Perform at your peak on every business trip',
    heroSub: 'Smart eating for jet lag, hotel dining, business entertaining, and staying energised across time zones — for frequent flyers who refuse to let travel derail their health.',
    topConcerns: ['Jet lag and nutrition timing — when to eat across time zones', 'Healthy options in airport lounges and hotel restaurants', 'Maintaining energy for back-to-back meetings', 'Avoiding weight gain during frequent travel', 'Staying focused and alert with the right foods', 'Managing corporate dining and client entertainment healthily'],
    sampleQuestion: 'I am flying London to Singapore for a 3-day conference. I land at 6am local time after a 13-hour flight. What should I eat on the plane and immediately after landing to minimise jet lag and be sharp for meetings starting at 9am?',
    color: '#534AB7',
    lightColor: '#EEEDFE',
    systemPromptAddition: 'The user is a business traveler focused on performance, energy, and maintaining health while traveling for work. Key priorities: jet lag management through strategic eating and fasting on flights, healthy choices in airport lounges and business hotels, maintaining mental clarity and energy for meetings, avoiding the energy crashes that come from poor airport/hotel food choices, managing weight during frequent travel, and navigating business entertainment meals healthily. Practical, time-efficient advice is essential — these users are busy.',
    metaTitle: 'NomadVital for Business Travelers — Eat Well and Perform Better on Work Trips',
    metaDescription: 'AI nutrition guidance for business travelers. Manage jet lag, eat healthily in hotels and airports, and maintain peak energy for meetings — in 50+ business destinations.',
    pageUrl: '/for/business-travelers',
  },
  {
    id: 'wellness',
    slug: 'wellness-travelers',
    name: 'Wellness & Yoga Traveler',
    emoji: '🧘',
    svgIcon: 'lotus',
    tagline: 'Mindful nutrition for wellness journeys',
    description: 'Wellness travelers, yoga retreat participants, digital nomads, and anyone seeking plant-based, mindful, or Ayurvedic eating abroad.',
    heroHeadline: 'Nourish your wellness journey',
    heroSub: 'Plant-based eating by destination, Ayurvedic food guidance, retreat nutrition, and local superfoods — for travelers who treat food as part of their wellness practice.',
    topConcerns: ['Plant-based and vegan eating by country', 'Ayurvedic food principles at specific destinations', 'Local superfoods and their authentic uses', 'Detox-friendly foods while traveling', 'Mindful eating in unfamiliar food environments', 'Supplement safety at wellness retreat destinations'],
    sampleQuestion: 'I am going to a 21-day yoga retreat in Rishikesh, India. I want to eat as sattvic and plant-based as possible. What local foods support this and what should I be careful about food safety wise?',
    color: '#A8725E',
    lightColor: '#F7EDE8',
    systemPromptAddition: 'The user is a wellness or yoga traveler interested in plant-based eating, mindful nutrition, and holistic health while traveling. Key priorities: vegan and vegetarian options available at the destination, Ayurvedic food principles if relevant to their destination (especially India), local superfoods and their authentic uses, foods that support a detox or cleansing intention, food safety for those eating at wellness retreats and local markets, and supplement safety at their destination. Use a warm, holistic tone that respects their wellness values.',
    metaTitle: 'NomadVital for Wellness Travelers — Plant-Based and Mindful Nutrition Abroad',
    metaDescription: 'Nutrition guidance for wellness and yoga travelers. Plant-based eating by country, Ayurvedic food guidance, local superfoods, and retreat nutrition for mindful travelers.',
    pageUrl: '/for/wellness-travelers',
  },
]

export const getPersonaById = (id) =>
  travelerPersonas.find(p => p.id === id) || travelerPersonas[0]

export const getPersonaBySlug = (slug) =>
  travelerPersonas.find(p => p.slug === slug) || travelerPersonas[0]
